package com.loveiparty.http.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.loveiparty.http.db.UserAsset;
import com.loveiparty.http.db.Comment;
import com.loveiparty.http.db.Coupon;
import com.loveiparty.http.db.ETicket;
import com.loveiparty.http.db.MyFavorite;
import com.loveiparty.http.db.Feedback;
import com.loveiparty.http.db.Message;
import com.loveiparty.http.db.NotificationPush;
import com.loveiparty.http.db.Order;
import com.loveiparty.http.db.Party;
import com.loveiparty.http.db.Talent;
import com.loveiparty.http.db.User;
import com.loveiparty.http.db.UrlString;

import com.loveiparty.http.db.UserAssetDao;
import com.loveiparty.http.db.CommentDao;
import com.loveiparty.http.db.CouponDao;
import com.loveiparty.http.db.ETicketDao;
import com.loveiparty.http.db.MyFavoriteDao;
import com.loveiparty.http.db.FeedbackDao;
import com.loveiparty.http.db.MessageDao;
import com.loveiparty.http.db.NotificationPushDao;
import com.loveiparty.http.db.OrderDao;
import com.loveiparty.http.db.PartyDao;
import com.loveiparty.http.db.TalentDao;
import com.loveiparty.http.db.UserDao;
import com.loveiparty.http.db.UrlStringDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userAssetDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig couponDaoConfig;
    private final DaoConfig eTicketDaoConfig;
    private final DaoConfig myFavoriteDaoConfig;
    private final DaoConfig feedbackDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig notificationPushDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig partyDaoConfig;
    private final DaoConfig talentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig urlStringDaoConfig;

    private final UserAssetDao userAssetDao;
    private final CommentDao commentDao;
    private final CouponDao couponDao;
    private final ETicketDao eTicketDao;
    private final MyFavoriteDao myFavoriteDao;
    private final FeedbackDao feedbackDao;
    private final MessageDao messageDao;
    private final NotificationPushDao notificationPushDao;
    private final OrderDao orderDao;
    private final PartyDao partyDao;
    private final TalentDao talentDao;
    private final UserDao userDao;
    private final UrlStringDao urlStringDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userAssetDaoConfig = daoConfigMap.get(UserAssetDao.class).clone();
        userAssetDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        couponDaoConfig = daoConfigMap.get(CouponDao.class).clone();
        couponDaoConfig.initIdentityScope(type);

        eTicketDaoConfig = daoConfigMap.get(ETicketDao.class).clone();
        eTicketDaoConfig.initIdentityScope(type);

        myFavoriteDaoConfig = daoConfigMap.get(MyFavoriteDao.class).clone();
        myFavoriteDaoConfig.initIdentityScope(type);

        feedbackDaoConfig = daoConfigMap.get(FeedbackDao.class).clone();
        feedbackDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        notificationPushDaoConfig = daoConfigMap.get(NotificationPushDao.class).clone();
        notificationPushDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        partyDaoConfig = daoConfigMap.get(PartyDao.class).clone();
        partyDaoConfig.initIdentityScope(type);

        talentDaoConfig = daoConfigMap.get(TalentDao.class).clone();
        talentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        urlStringDaoConfig = daoConfigMap.get(UrlStringDao.class).clone();
        urlStringDaoConfig.initIdentityScope(type);

        userAssetDao = new UserAssetDao(userAssetDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        couponDao = new CouponDao(couponDaoConfig, this);
        eTicketDao = new ETicketDao(eTicketDaoConfig, this);
        myFavoriteDao = new MyFavoriteDao(myFavoriteDaoConfig, this);
        feedbackDao = new FeedbackDao(feedbackDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        notificationPushDao = new NotificationPushDao(notificationPushDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        partyDao = new PartyDao(partyDaoConfig, this);
        talentDao = new TalentDao(talentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        urlStringDao = new UrlStringDao(urlStringDaoConfig, this);

        registerDao(UserAsset.class, userAssetDao);
        registerDao(Comment.class, commentDao);
        registerDao(Coupon.class, couponDao);
        registerDao(ETicket.class, eTicketDao);
        registerDao(MyFavorite.class, myFavoriteDao);
        registerDao(Feedback.class, feedbackDao);
        registerDao(Message.class, messageDao);
        registerDao(NotificationPush.class, notificationPushDao);
        registerDao(Order.class, orderDao);
        registerDao(Party.class, partyDao);
        registerDao(Talent.class, talentDao);
        registerDao(User.class, userDao);
        registerDao(UrlString.class, urlStringDao);
    }
    
    public void clear() {
        userAssetDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        couponDaoConfig.getIdentityScope().clear();
        eTicketDaoConfig.getIdentityScope().clear();
        myFavoriteDaoConfig.getIdentityScope().clear();
        feedbackDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        notificationPushDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        partyDaoConfig.getIdentityScope().clear();
        talentDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        urlStringDaoConfig.getIdentityScope().clear();
    }

    public UserAssetDao getUserAssetDao() {
        return userAssetDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public CouponDao getCouponDao() {
        return couponDao;
    }

    public ETicketDao getETicketDao() {
        return eTicketDao;
    }

    public MyFavoriteDao getMyFavoriteDao() {
        return myFavoriteDao;
    }

    public FeedbackDao getFeedbackDao() {
        return feedbackDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public NotificationPushDao getNotificationPushDao() {
        return notificationPushDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public PartyDao getPartyDao() {
        return partyDao;
    }

    public TalentDao getTalentDao() {
        return talentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UrlStringDao getUrlStringDao() {
        return urlStringDao;
    }

}
