package com.loveiparty.http.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private String avatar;
    private String content;
    private java.util.Date created_at;
    private String nickname;
    private Integer sex;
    private Integer user_id;
    private String party_id;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String avatar, String content, java.util.Date created_at, String nickname, Integer sex, Integer user_id, String party_id) {
        this.id = id;
        this.avatar = avatar;
        this.content = content;
        this.created_at = created_at;
        this.nickname = nickname;
        this.sex = sex;
        this.user_id = user_id;
        this.party_id = party_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getParty_id() {
        return party_id;
    }

    public void setParty_id(String party_id) {
        this.party_id = party_id;
    }

}
