package com.loveiparty.http.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER".
 */
public class Order extends com.loveiparty.http.Bean.BaseHttpBean  {

    private Long id;
    private String order_id;
    private java.util.Date order_time;
    private String party_id;
    private java.util.Date party_time;
    private Integer status;
    private String user_avatar;
    private Integer user_id;
    private String user_nickname;
    private Integer user_sex;
    private String objectId;
    private Integer refund_state;
    private java.util.Date created_time;
    private String phone;
    private Integer sex;
    private Integer isshare;
    private String share_user_id;
    private String share_id;
    private String paytime;
    private String party_title;
    private Integer issendmsg;
    private Integer send_notifications;
    private Integer is_del;
    private Integer discount;
    private String out_trade_no;
    private String bonus_id;
    private Integer price;
    private java.util.Date update_time;

    public Order() {
    }

    public Order(Long id) {
        this.id = id;
    }

    public Order(Long id, String order_id, java.util.Date order_time, String party_id, java.util.Date party_time, Integer status, String user_avatar, Integer user_id, String user_nickname, Integer user_sex, String objectId, Integer refund_state, java.util.Date created_time, String phone, Integer sex, Integer isshare, String share_user_id, String share_id, String paytime, String party_title, Integer issendmsg, Integer send_notifications, Integer is_del, Integer discount, String out_trade_no, String bonus_id, Integer price, java.util.Date update_time) {
        this.id = id;
        this.order_id = order_id;
        this.order_time = order_time;
        this.party_id = party_id;
        this.party_time = party_time;
        this.status = status;
        this.user_avatar = user_avatar;
        this.user_id = user_id;
        this.user_nickname = user_nickname;
        this.user_sex = user_sex;
        this.objectId = objectId;
        this.refund_state = refund_state;
        this.created_time = created_time;
        this.phone = phone;
        this.sex = sex;
        this.isshare = isshare;
        this.share_user_id = share_user_id;
        this.share_id = share_id;
        this.paytime = paytime;
        this.party_title = party_title;
        this.issendmsg = issendmsg;
        this.send_notifications = send_notifications;
        this.is_del = is_del;
        this.discount = discount;
        this.out_trade_no = out_trade_no;
        this.bonus_id = bonus_id;
        this.price = price;
        this.update_time = update_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public java.util.Date getOrder_time() {
        return order_time;
    }

    public void setOrder_time(java.util.Date order_time) {
        this.order_time = order_time;
    }

    public String getParty_id() {
        return party_id;
    }

    public void setParty_id(String party_id) {
        this.party_id = party_id;
    }

    public java.util.Date getParty_time() {
        return party_time;
    }

    public void setParty_time(java.util.Date party_time) {
        this.party_time = party_time;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUser_avatar() {
        return user_avatar;
    }

    public void setUser_avatar(String user_avatar) {
        this.user_avatar = user_avatar;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getUser_nickname() {
        return user_nickname;
    }

    public void setUser_nickname(String user_nickname) {
        this.user_nickname = user_nickname;
    }

    public Integer getUser_sex() {
        return user_sex;
    }

    public void setUser_sex(Integer user_sex) {
        this.user_sex = user_sex;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public Integer getRefund_state() {
        return refund_state;
    }

    public void setRefund_state(Integer refund_state) {
        this.refund_state = refund_state;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getIsshare() {
        return isshare;
    }

    public void setIsshare(Integer isshare) {
        this.isshare = isshare;
    }

    public String getShare_user_id() {
        return share_user_id;
    }

    public void setShare_user_id(String share_user_id) {
        this.share_user_id = share_user_id;
    }

    public String getShare_id() {
        return share_id;
    }

    public void setShare_id(String share_id) {
        this.share_id = share_id;
    }

    public String getPaytime() {
        return paytime;
    }

    public void setPaytime(String paytime) {
        this.paytime = paytime;
    }

    public String getParty_title() {
        return party_title;
    }

    public void setParty_title(String party_title) {
        this.party_title = party_title;
    }

    public Integer getIssendmsg() {
        return issendmsg;
    }

    public void setIssendmsg(Integer issendmsg) {
        this.issendmsg = issendmsg;
    }

    public Integer getSend_notifications() {
        return send_notifications;
    }

    public void setSend_notifications(Integer send_notifications) {
        this.send_notifications = send_notifications;
    }

    public Integer getIs_del() {
        return is_del;
    }

    public void setIs_del(Integer is_del) {
        this.is_del = is_del;
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public String getOut_trade_no() {
        return out_trade_no;
    }

    public void setOut_trade_no(String out_trade_no) {
        this.out_trade_no = out_trade_no;
    }

    public String getBonus_id() {
        return bonus_id;
    }

    public void setBonus_id(String bonus_id) {
        this.bonus_id = bonus_id;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

}
