package com.loveiparty.http.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.loveiparty.http.db.Party;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PARTY".
*/
public class PartyDao extends AbstractDao<Party, Long> {

    public static final String TABLENAME = "PARTY";

    /**
     * Properties of entity Party.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Address_text = new Property(2, String.class, "address_text", false, "ADDRESS_TEXT");
        public final static Property Address_url = new Property(3, String.class, "address_url", false, "ADDRESS_URL");
        public final static Property Address_thumbnail = new Property(4, String.class, "address_thumbnail", false, "ADDRESS_THUMBNAIL");
        public final static Property End_time = new Property(5, java.util.Date.class, "end_time", false, "END_TIME");
        public final static Property Favorite_num = new Property(6, Integer.class, "favorite_num", false, "FAVORITE_NUM");
        public final static Property Head_photo = new Property(7, String.class, "head_photo", false, "HEAD_PHOTO");
        public final static Property In_progress = new Property(8, Integer.class, "in_progress", false, "IN_PROGRESS");
        public final static Property Last_update_time = new Property(9, java.util.Date.class, "last_update_time", false, "LAST_UPDATE_TIME");
        public final static Property Least_num = new Property(10, Integer.class, "least_num", false, "LEAST_NUM");
        public final static Property Limited = new Property(11, Integer.class, "limited", false, "LIMITED");
        public final static Property Maximum_num = new Property(12, Integer.class, "maximum_num", false, "MAXIMUM_NUM");
        public final static Property Old_price_man = new Property(13, Integer.class, "old_price_man", false, "OLD_PRICE_MAN");
        public final static Property Old_price_woman = new Property(14, Integer.class, "old_price_woman", false, "OLD_PRICE_WOMAN");
        public final static Property Party_id = new Property(15, Integer.class, "party_id", false, "PARTY_ID");
        public final static Property Pic_base_url = new Property(16, String.class, "pic_base_url", false, "PIC_BASE_URL");
        public final static Property Price_man = new Property(17, Integer.class, "price_man", false, "PRICE_MAN");
        public final static Property Price_woman = new Property(18, Integer.class, "price_woman", false, "PRICE_WOMAN");
        public final static Property Publisher_avatar = new Property(19, String.class, "publisher_avatar", false, "PUBLISHER_AVATAR");
        public final static Property Publisher_id = new Property(20, Integer.class, "publisher_id", false, "PUBLISHER_ID");
        public final static Property Publisher_name = new Property(21, String.class, "publisher_name", false, "PUBLISHER_NAME");
        public final static Property Publisher_star = new Property(22, Integer.class, "publisher_star", false, "PUBLISHER_STAR");
        public final static Property Recommend = new Property(23, String.class, "recommend", false, "RECOMMEND");
        public final static Property Sold_num = new Property(24, Integer.class, "sold_num", false, "SOLD_NUM");
        public final static Property Start_time = new Property(25, java.util.Date.class, "start_time", false, "START_TIME");
        public final static Property Time_text = new Property(26, String.class, "time_text", false, "TIME_TEXT");
        public final static Property Time_type = new Property(27, Integer.class, "time_type", false, "TIME_TYPE");
        public final static Property Title = new Property(28, String.class, "title", false, "TITLE");
        public final static Property Types = new Property(29, String.class, "types", false, "TYPES");
        public final static Property Week_activity = new Property(30, Integer.class, "week_activity", false, "WEEK_ACTIVITY");
        public final static Property Only = new Property(31, String.class, "only", false, "ONLY");
        public final static Property Leastnum = new Property(32, Integer.class, "leastnum", false, "LEASTNUM");
        public final static Property Sold = new Property(33, Integer.class, "sold", false, "SOLD");
        public final static Property Phone = new Property(34, String.class, "phone", false, "PHONE");
        public final static Property Description = new Property(35, String.class, "description", false, "DESCRIPTION");
        public final static Property Content = new Property(36, String.class, "content", false, "CONTENT");
        public final static Property Note = new Property(37, String.class, "note", false, "NOTE");
        public final static Property Created_time = new Property(38, java.util.Date.class, "created_time", false, "CREATED_TIME");
        public final static Property Photoids = new Property(39, String.class, "photoids", false, "PHOTOIDS");
        public final static Property Wechatgroup = new Property(40, String.class, "wechatgroup", false, "WECHATGROUP");
        public final static Property Customphoto = new Property(41, String.class, "customphoto", false, "CUSTOMPHOTO");
        public final static Property Is_delete = new Property(42, Integer.class, "is_delete", false, "IS_DELETE");
        public final static Property Type_ids = new Property(43, Integer.class, "type_ids", false, "TYPE_IDS");
        public final static Property Deadline_time = new Property(44, String.class, "deadline_time", false, "DEADLINE_TIME");
        public final static Property User_id = new Property(45, String.class, "user_id", false, "USER_ID");
        public final static Property Is_audited = new Property(46, Boolean.class, "is_audited", false, "IS_AUDITED");
        public final static Property Is_available = new Property(47, Boolean.class, "is_available", false, "IS_AVAILABLE");
        public final static Property Update_time = new Property(48, java.util.Date.class, "update_time", false, "UPDATE_TIME");
    };


    public PartyDao(DaoConfig config) {
        super(config);
    }
    
    public PartyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PARTY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"ADDRESS_TEXT\" TEXT," + // 2: address_text
                "\"ADDRESS_URL\" TEXT," + // 3: address_url
                "\"ADDRESS_THUMBNAIL\" TEXT," + // 4: address_thumbnail
                "\"END_TIME\" INTEGER," + // 5: end_time
                "\"FAVORITE_NUM\" INTEGER," + // 6: favorite_num
                "\"HEAD_PHOTO\" TEXT," + // 7: head_photo
                "\"IN_PROGRESS\" INTEGER," + // 8: in_progress
                "\"LAST_UPDATE_TIME\" INTEGER," + // 9: last_update_time
                "\"LEAST_NUM\" INTEGER," + // 10: least_num
                "\"LIMITED\" INTEGER," + // 11: limited
                "\"MAXIMUM_NUM\" INTEGER," + // 12: maximum_num
                "\"OLD_PRICE_MAN\" INTEGER," + // 13: old_price_man
                "\"OLD_PRICE_WOMAN\" INTEGER," + // 14: old_price_woman
                "\"PARTY_ID\" INTEGER," + // 15: party_id
                "\"PIC_BASE_URL\" TEXT," + // 16: pic_base_url
                "\"PRICE_MAN\" INTEGER," + // 17: price_man
                "\"PRICE_WOMAN\" INTEGER," + // 18: price_woman
                "\"PUBLISHER_AVATAR\" TEXT," + // 19: publisher_avatar
                "\"PUBLISHER_ID\" INTEGER," + // 20: publisher_id
                "\"PUBLISHER_NAME\" TEXT," + // 21: publisher_name
                "\"PUBLISHER_STAR\" INTEGER," + // 22: publisher_star
                "\"RECOMMEND\" TEXT," + // 23: recommend
                "\"SOLD_NUM\" INTEGER," + // 24: sold_num
                "\"START_TIME\" INTEGER," + // 25: start_time
                "\"TIME_TEXT\" TEXT," + // 26: time_text
                "\"TIME_TYPE\" INTEGER," + // 27: time_type
                "\"TITLE\" TEXT," + // 28: title
                "\"TYPES\" TEXT," + // 29: types
                "\"WEEK_ACTIVITY\" INTEGER," + // 30: week_activity
                "\"ONLY\" TEXT," + // 31: only
                "\"LEASTNUM\" INTEGER," + // 32: leastnum
                "\"SOLD\" INTEGER," + // 33: sold
                "\"PHONE\" TEXT," + // 34: phone
                "\"DESCRIPTION\" TEXT," + // 35: description
                "\"CONTENT\" TEXT," + // 36: content
                "\"NOTE\" TEXT," + // 37: note
                "\"CREATED_TIME\" INTEGER," + // 38: created_time
                "\"PHOTOIDS\" TEXT," + // 39: photoids
                "\"WECHATGROUP\" TEXT," + // 40: wechatgroup
                "\"CUSTOMPHOTO\" TEXT," + // 41: customphoto
                "\"IS_DELETE\" INTEGER," + // 42: is_delete
                "\"TYPE_IDS\" INTEGER," + // 43: type_ids
                "\"DEADLINE_TIME\" TEXT," + // 44: deadline_time
                "\"USER_ID\" TEXT," + // 45: user_id
                "\"IS_AUDITED\" INTEGER," + // 46: is_audited
                "\"IS_AVAILABLE\" INTEGER," + // 47: is_available
                "\"UPDATE_TIME\" INTEGER);"); // 48: update_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PARTY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Party entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String address_text = entity.getAddress_text();
        if (address_text != null) {
            stmt.bindString(3, address_text);
        }
 
        String address_url = entity.getAddress_url();
        if (address_url != null) {
            stmt.bindString(4, address_url);
        }
 
        String address_thumbnail = entity.getAddress_thumbnail();
        if (address_thumbnail != null) {
            stmt.bindString(5, address_thumbnail);
        }
 
        java.util.Date end_time = entity.getEnd_time();
        if (end_time != null) {
            stmt.bindLong(6, end_time.getTime());
        }
 
        Integer favorite_num = entity.getFavorite_num();
        if (favorite_num != null) {
            stmt.bindLong(7, favorite_num);
        }
 
        String head_photo = entity.getHead_photo();
        if (head_photo != null) {
            stmt.bindString(8, head_photo);
        }
 
        Integer in_progress = entity.getIn_progress();
        if (in_progress != null) {
            stmt.bindLong(9, in_progress);
        }
 
        java.util.Date last_update_time = entity.getLast_update_time();
        if (last_update_time != null) {
            stmt.bindLong(10, last_update_time.getTime());
        }
 
        Integer least_num = entity.getLeast_num();
        if (least_num != null) {
            stmt.bindLong(11, least_num);
        }
 
        Integer limited = entity.getLimited();
        if (limited != null) {
            stmt.bindLong(12, limited);
        }
 
        Integer maximum_num = entity.getMaximum_num();
        if (maximum_num != null) {
            stmt.bindLong(13, maximum_num);
        }
 
        Integer old_price_man = entity.getOld_price_man();
        if (old_price_man != null) {
            stmt.bindLong(14, old_price_man);
        }
 
        Integer old_price_woman = entity.getOld_price_woman();
        if (old_price_woman != null) {
            stmt.bindLong(15, old_price_woman);
        }
 
        Integer party_id = entity.getParty_id();
        if (party_id != null) {
            stmt.bindLong(16, party_id);
        }
 
        String pic_base_url = entity.getPic_base_url();
        if (pic_base_url != null) {
            stmt.bindString(17, pic_base_url);
        }
 
        Integer price_man = entity.getPrice_man();
        if (price_man != null) {
            stmt.bindLong(18, price_man);
        }
 
        Integer price_woman = entity.getPrice_woman();
        if (price_woman != null) {
            stmt.bindLong(19, price_woman);
        }
 
        String publisher_avatar = entity.getPublisher_avatar();
        if (publisher_avatar != null) {
            stmt.bindString(20, publisher_avatar);
        }
 
        Integer publisher_id = entity.getPublisher_id();
        if (publisher_id != null) {
            stmt.bindLong(21, publisher_id);
        }
 
        String publisher_name = entity.getPublisher_name();
        if (publisher_name != null) {
            stmt.bindString(22, publisher_name);
        }
 
        Integer publisher_star = entity.getPublisher_star();
        if (publisher_star != null) {
            stmt.bindLong(23, publisher_star);
        }
 
        String recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindString(24, recommend);
        }
 
        Integer sold_num = entity.getSold_num();
        if (sold_num != null) {
            stmt.bindLong(25, sold_num);
        }
 
        java.util.Date start_time = entity.getStart_time();
        if (start_time != null) {
            stmt.bindLong(26, start_time.getTime());
        }
 
        String time_text = entity.getTime_text();
        if (time_text != null) {
            stmt.bindString(27, time_text);
        }
 
        Integer time_type = entity.getTime_type();
        if (time_type != null) {
            stmt.bindLong(28, time_type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(29, title);
        }
 
        String types = entity.getTypes();
        if (types != null) {
            stmt.bindString(30, types);
        }
 
        Integer week_activity = entity.getWeek_activity();
        if (week_activity != null) {
            stmt.bindLong(31, week_activity);
        }
 
        String only = entity.getOnly();
        if (only != null) {
            stmt.bindString(32, only);
        }
 
        Integer leastnum = entity.getLeastnum();
        if (leastnum != null) {
            stmt.bindLong(33, leastnum);
        }
 
        Integer sold = entity.getSold();
        if (sold != null) {
            stmt.bindLong(34, sold);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(35, phone);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(36, description);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(37, content);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(38, note);
        }
 
        java.util.Date created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindLong(39, created_time.getTime());
        }
 
        String photoids = entity.getPhotoids();
        if (photoids != null) {
            stmt.bindString(40, photoids);
        }
 
        String wechatgroup = entity.getWechatgroup();
        if (wechatgroup != null) {
            stmt.bindString(41, wechatgroup);
        }
 
        String customphoto = entity.getCustomphoto();
        if (customphoto != null) {
            stmt.bindString(42, customphoto);
        }
 
        Integer is_delete = entity.getIs_delete();
        if (is_delete != null) {
            stmt.bindLong(43, is_delete);
        }
 
        Integer type_ids = entity.getType_ids();
        if (type_ids != null) {
            stmt.bindLong(44, type_ids);
        }
 
        String deadline_time = entity.getDeadline_time();
        if (deadline_time != null) {
            stmt.bindString(45, deadline_time);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(46, user_id);
        }
 
        Boolean is_audited = entity.getIs_audited();
        if (is_audited != null) {
            stmt.bindLong(47, is_audited ? 1L: 0L);
        }
 
        Boolean is_available = entity.getIs_available();
        if (is_available != null) {
            stmt.bindLong(48, is_available ? 1L: 0L);
        }
 
        java.util.Date update_time = entity.getUpdate_time();
        if (update_time != null) {
            stmt.bindLong(49, update_time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Party readEntity(Cursor cursor, int offset) {
        Party entity = new Party( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // address_text
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address_url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // address_thumbnail
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // end_time
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // favorite_num
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // head_photo
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // in_progress
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)), // last_update_time
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // least_num
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // limited
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // maximum_num
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // old_price_man
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // old_price_woman
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // party_id
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // pic_base_url
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // price_man
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18), // price_woman
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // publisher_avatar
            cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20), // publisher_id
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // publisher_name
            cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22), // publisher_star
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // recommend
            cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24), // sold_num
            cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)), // start_time
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // time_text
            cursor.isNull(offset + 27) ? null : cursor.getInt(offset + 27), // time_type
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // title
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // types
            cursor.isNull(offset + 30) ? null : cursor.getInt(offset + 30), // week_activity
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // only
            cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32), // leastnum
            cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33), // sold
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // phone
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // description
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // content
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // note
            cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)), // created_time
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // photoids
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // wechatgroup
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // customphoto
            cursor.isNull(offset + 42) ? null : cursor.getInt(offset + 42), // is_delete
            cursor.isNull(offset + 43) ? null : cursor.getInt(offset + 43), // type_ids
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // deadline_time
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // user_id
            cursor.isNull(offset + 46) ? null : cursor.getShort(offset + 46) != 0, // is_audited
            cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0, // is_available
            cursor.isNull(offset + 48) ? null : new java.util.Date(cursor.getLong(offset + 48)) // update_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Party entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAddress_text(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress_url(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAddress_thumbnail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEnd_time(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setFavorite_num(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setHead_photo(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIn_progress(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setLast_update_time(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
        entity.setLeast_num(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setLimited(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setMaximum_num(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setOld_price_man(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setOld_price_woman(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setParty_id(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setPic_base_url(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPrice_man(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setPrice_woman(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
        entity.setPublisher_avatar(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setPublisher_id(cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20));
        entity.setPublisher_name(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPublisher_star(cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22));
        entity.setRecommend(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSold_num(cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24));
        entity.setStart_time(cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)));
        entity.setTime_text(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setTime_type(cursor.isNull(offset + 27) ? null : cursor.getInt(offset + 27));
        entity.setTitle(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTypes(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWeek_activity(cursor.isNull(offset + 30) ? null : cursor.getInt(offset + 30));
        entity.setOnly(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setLeastnum(cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32));
        entity.setSold(cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33));
        entity.setPhone(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setDescription(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setContent(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setNote(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setCreated_time(cursor.isNull(offset + 38) ? null : new java.util.Date(cursor.getLong(offset + 38)));
        entity.setPhotoids(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setWechatgroup(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setCustomphoto(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setIs_delete(cursor.isNull(offset + 42) ? null : cursor.getInt(offset + 42));
        entity.setType_ids(cursor.isNull(offset + 43) ? null : cursor.getInt(offset + 43));
        entity.setDeadline_time(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setUser_id(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setIs_audited(cursor.isNull(offset + 46) ? null : cursor.getShort(offset + 46) != 0);
        entity.setIs_available(cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47) != 0);
        entity.setUpdate_time(cursor.isNull(offset + 48) ? null : new java.util.Date(cursor.getLong(offset + 48)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Party entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Party entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
