package com.loveiparty.http.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TALENT".
 */
public class Talent extends com.loveiparty.http.Bean.BaseTalentBean  {

    private Long id;
    private String introduction;
    private String talent_avatar;
    private String talent_details;
    private String talent_name;
    private String talent_phone;
    private Double talent_stars;
    private Integer talent_types;
    private Integer user_id;
    private String objectId;
    private String real_name;
    private String avatar;
    private Integer identify;
    private String city;
    private String province;
    private String wechat_account;
    private String phone;
    private String photo_ids;
    private String details;
    private Integer type_ids;
    private java.util.Date created_time;
    private Integer is_audited;
    private java.util.Date update_time;

    public Talent() {
    }

    public Talent(Long id) {
        this.id = id;
    }

    public Talent(Long id, String introduction, String talent_avatar, String talent_details, String talent_name, String talent_phone, Double talent_stars, Integer talent_types, Integer user_id, String objectId, String real_name, String avatar, Integer identify, String city, String province, String wechat_account, String phone, String photo_ids, String details, Integer type_ids, java.util.Date created_time, Integer is_audited, java.util.Date update_time) {
        this.id = id;
        this.introduction = introduction;
        this.talent_avatar = talent_avatar;
        this.talent_details = talent_details;
        this.talent_name = talent_name;
        this.talent_phone = talent_phone;
        this.talent_stars = talent_stars;
        this.talent_types = talent_types;
        this.user_id = user_id;
        this.objectId = objectId;
        this.real_name = real_name;
        this.avatar = avatar;
        this.identify = identify;
        this.city = city;
        this.province = province;
        this.wechat_account = wechat_account;
        this.phone = phone;
        this.photo_ids = photo_ids;
        this.details = details;
        this.type_ids = type_ids;
        this.created_time = created_time;
        this.is_audited = is_audited;
        this.update_time = update_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getTalent_avatar() {
        return talent_avatar;
    }

    public void setTalent_avatar(String talent_avatar) {
        this.talent_avatar = talent_avatar;
    }

    public String getTalent_details() {
        return talent_details;
    }

    public void setTalent_details(String talent_details) {
        this.talent_details = talent_details;
    }

    public String getTalent_name() {
        return talent_name;
    }

    public void setTalent_name(String talent_name) {
        this.talent_name = talent_name;
    }

    public String getTalent_phone() {
        return talent_phone;
    }

    public void setTalent_phone(String talent_phone) {
        this.talent_phone = talent_phone;
    }

    public Double getTalent_stars() {
        return talent_stars;
    }

    public void setTalent_stars(Double talent_stars) {
        this.talent_stars = talent_stars;
    }

    public Integer getTalent_types() {
        return talent_types;
    }

    public void setTalent_types(Integer talent_types) {
        this.talent_types = talent_types;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getReal_name() {
        return real_name;
    }

    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getIdentify() {
        return identify;
    }

    public void setIdentify(Integer identify) {
        this.identify = identify;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getWechat_account() {
        return wechat_account;
    }

    public void setWechat_account(String wechat_account) {
        this.wechat_account = wechat_account;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoto_ids() {
        return photo_ids;
    }

    public void setPhoto_ids(String photo_ids) {
        this.photo_ids = photo_ids;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public Integer getType_ids() {
        return type_ids;
    }

    public void setType_ids(Integer type_ids) {
        this.type_ids = type_ids;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public Integer getIs_audited() {
        return is_audited;
    }

    public void setIs_audited(Integer is_audited) {
        this.is_audited = is_audited;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

}
