package com.loveiparty.http.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_ASSET".
 */
public class UserAsset {

    private Long id;
    private String objectId;
    private String user_id;
    private String total_fee;
    private String fee_state;
    private java.util.Date updated_time;

    public UserAsset() {
    }

    public UserAsset(Long id) {
        this.id = id;
    }

    public UserAsset(Long id, String objectId, String user_id, String total_fee, String fee_state, java.util.Date updated_time) {
        this.id = id;
        this.objectId = objectId;
        this.user_id = user_id;
        this.total_fee = total_fee;
        this.fee_state = fee_state;
        this.updated_time = updated_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTotal_fee() {
        return total_fee;
    }

    public void setTotal_fee(String total_fee) {
        this.total_fee = total_fee;
    }

    public String getFee_state() {
        return fee_state;
    }

    public void setFee_state(String fee_state) {
        this.fee_state = fee_state;
    }

    public java.util.Date getUpdated_time() {
        return updated_time;
    }

    public void setUpdated_time(java.util.Date updated_time) {
        this.updated_time = updated_time;
    }

}
