package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMENT".
 */
public class Comment {

    private Long id;
    private String objectId;
    private String user_id;
    private java.util.Date created_time;
    private java.util.Date updated_time;
    private String username;
    private String order_id;
    private String party_id;
    private String stars;
    private String content;
    private String photos;
    private String is_anonymous;
    private String status;

    public Comment() {
    }

    public Comment(Long id) {
        this.id = id;
    }

    public Comment(Long id, String objectId, String user_id, java.util.Date created_time, java.util.Date updated_time, String username, String order_id, String party_id, String stars, String content, String photos, String is_anonymous, String status) {
        this.id = id;
        this.objectId = objectId;
        this.user_id = user_id;
        this.created_time = created_time;
        this.updated_time = updated_time;
        this.username = username;
        this.order_id = order_id;
        this.party_id = party_id;
        this.stars = stars;
        this.content = content;
        this.photos = photos;
        this.is_anonymous = is_anonymous;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public java.util.Date getUpdated_time() {
        return updated_time;
    }

    public void setUpdated_time(java.util.Date updated_time) {
        this.updated_time = updated_time;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getParty_id() {
        return party_id;
    }

    public void setParty_id(String party_id) {
        this.party_id = party_id;
    }

    public String getStars() {
        return stars;
    }

    public void setStars(String stars) {
        this.stars = stars;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPhotos() {
        return photos;
    }

    public void setPhotos(String photos) {
        this.photos = photos;
    }

    public String getIs_anonymous() {
        return is_anonymous;
    }

    public void setIs_anonymous(String is_anonymous) {
        this.is_anonymous = is_anonymous;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
