package com.zongbutech.iparty.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.zongbutech.iparty.db.ETicket;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ETICKET".
*/
public class ETicketDao extends AbstractDao<ETicket, Long> {

    public static final String TABLENAME = "ETICKET";

    /**
     * Properties of entity ETicket.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Order_id = new Property(2, String.class, "order_id", false, "ORDER_ID");
        public final static Property User_id = new Property(3, String.class, "user_id", false, "USER_ID");
        public final static Property Party_id = new Property(4, String.class, "party_id", false, "PARTY_ID");
        public final static Property Qrcode = new Property(5, String.class, "qrcode", false, "QRCODE");
        public final static Property Status = new Property(6, String.class, "status", false, "STATUS");
        public final static Property Wechatgroup = new Property(7, String.class, "wechatgroup", false, "WECHATGROUP");
        public final static Property Created_time = new Property(8, java.util.Date.class, "created_time", false, "CREATED_TIME");
        public final static Property Updated_time = new Property(9, java.util.Date.class, "updated_time", false, "UPDATED_TIME");
    };


    public ETicketDao(DaoConfig config) {
        super(config);
    }
    
    public ETicketDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ETICKET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"ORDER_ID\" TEXT," + // 2: order_id
                "\"USER_ID\" TEXT," + // 3: user_id
                "\"PARTY_ID\" TEXT," + // 4: party_id
                "\"QRCODE\" TEXT," + // 5: qrcode
                "\"STATUS\" TEXT," + // 6: status
                "\"WECHATGROUP\" TEXT," + // 7: wechatgroup
                "\"CREATED_TIME\" INTEGER," + // 8: created_time
                "\"UPDATED_TIME\" INTEGER);"); // 9: updated_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ETICKET\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ETicket entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String order_id = entity.getOrder_id();
        if (order_id != null) {
            stmt.bindString(3, order_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(4, user_id);
        }
 
        String party_id = entity.getParty_id();
        if (party_id != null) {
            stmt.bindString(5, party_id);
        }
 
        String qrcode = entity.getQrcode();
        if (qrcode != null) {
            stmt.bindString(6, qrcode);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(7, status);
        }
 
        String wechatgroup = entity.getWechatgroup();
        if (wechatgroup != null) {
            stmt.bindString(8, wechatgroup);
        }
 
        java.util.Date created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindLong(9, created_time.getTime());
        }
 
        java.util.Date updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindLong(10, updated_time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ETicket readEntity(Cursor cursor, int offset) {
        ETicket entity = new ETicket( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // order_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // user_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // party_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // qrcode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // status
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // wechatgroup
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // created_time
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)) // updated_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ETicket entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOrder_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUser_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParty_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQrcode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStatus(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWechatgroup(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreated_time(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setUpdated_time(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ETicket entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ETicket entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
