package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ETICKET".
 */
public class ETicket {

    private Long id;
    private String objectId;
    private String order_id;
    private String user_id;
    private String party_id;
    private String qrcode;
    private String status;
    private String wechatgroup;
    private java.util.Date created_time;
    private java.util.Date updated_time;

    public ETicket() {
    }

    public ETicket(Long id) {
        this.id = id;
    }

    public ETicket(Long id, String objectId, String order_id, String user_id, String party_id, String qrcode, String status, String wechatgroup, java.util.Date created_time, java.util.Date updated_time) {
        this.id = id;
        this.objectId = objectId;
        this.order_id = order_id;
        this.user_id = user_id;
        this.party_id = party_id;
        this.qrcode = qrcode;
        this.status = status;
        this.wechatgroup = wechatgroup;
        this.created_time = created_time;
        this.updated_time = updated_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getParty_id() {
        return party_id;
    }

    public void setParty_id(String party_id) {
        this.party_id = party_id;
    }

    public String getQrcode() {
        return qrcode;
    }

    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getWechatgroup() {
        return wechatgroup;
    }

    public void setWechatgroup(String wechatgroup) {
        this.wechatgroup = wechatgroup;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public java.util.Date getUpdated_time() {
        return updated_time;
    }

    public void setUpdated_time(java.util.Date updated_time) {
        this.updated_time = updated_time;
    }

}
