package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FEEDBACK".
 */
public class Feedback {

    private Long id;
    private String objectId;
    private String content;
    private String contact;
    private String user_id;
    private String user_ip;
    private java.util.Date created_time;

    public Feedback() {
    }

    public Feedback(Long id) {
        this.id = id;
    }

    public Feedback(Long id, String objectId, String content, String contact, String user_id, String user_ip, java.util.Date created_time) {
        this.id = id;
        this.objectId = objectId;
        this.content = content;
        this.contact = contact;
        this.user_id = user_id;
        this.user_ip = user_ip;
        this.created_time = created_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_ip() {
        return user_ip;
    }

    public void setUser_ip(String user_ip) {
        this.user_ip = user_ip;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

}
