package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_FAVORITE".
 */
public class MyFavorite {

    private Long id;
    private String objectId;
    private String user_id;
    private String party_id;
    private java.util.Date created_time;

    public MyFavorite() {
    }

    public MyFavorite(Long id) {
        this.id = id;
    }

    public MyFavorite(Long id, String objectId, String user_id, String party_id, java.util.Date created_time) {
        this.id = id;
        this.objectId = objectId;
        this.user_id = user_id;
        this.party_id = party_id;
        this.created_time = created_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getParty_id() {
        return party_id;
    }

    public void setParty_id(String party_id) {
        this.party_id = party_id;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

}
