package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFICATION_PUSH".
 */
public class NotificationPush {

    private Long id;
    private String objectId;
    private String user_id;
    private String content;
    private String send_state;
    private Boolean is_read;
    private String extras;
    private java.util.Date created_time;
    private java.util.Date updated_time;

    public NotificationPush() {
    }

    public NotificationPush(Long id) {
        this.id = id;
    }

    public NotificationPush(Long id, String objectId, String user_id, String content, String send_state, Boolean is_read, String extras, java.util.Date created_time, java.util.Date updated_time) {
        this.id = id;
        this.objectId = objectId;
        this.user_id = user_id;
        this.content = content;
        this.send_state = send_state;
        this.is_read = is_read;
        this.extras = extras;
        this.created_time = created_time;
        this.updated_time = updated_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSend_state() {
        return send_state;
    }

    public void setSend_state(String send_state) {
        this.send_state = send_state;
    }

    public Boolean getIs_read() {
        return is_read;
    }

    public void setIs_read(Boolean is_read) {
        this.is_read = is_read;
    }

    public String getExtras() {
        return extras;
    }

    public void setExtras(String extras) {
        this.extras = extras;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public java.util.Date getUpdated_time() {
        return updated_time;
    }

    public void setUpdated_time(java.util.Date updated_time) {
        this.updated_time = updated_time;
    }

}
