package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PARTY".
 */
public class Party {

    private Long id;
    private String objectId;
    private String title;
    private String only;
    private Integer old_price_man;
    private Integer old_price_woman;
    private Integer price_man;
    private Integer price_woman;
    private java.util.Date end_time;
    private Integer favorite_num;
    private Integer leastnum;
    private Integer sold;
    private String address;
    private String addressurl;
    private String address_thumbnail;
    private String phone;
    private String description;
    private String content;
    private String note;
    private String pic_base_url;
    private java.util.Date created_time;
    private String photoids;
    private String headphoto;
    private String wechatgroup;
    private String customphoto;
    private Integer is_delete;
    private Integer type_ids;
    private Integer limited;
    private Integer maximum_num;
    private java.util.Date start_time;
    private String deadline_time;
    private Integer time_type;
    private String time_text;
    private String user_id;
    private Boolean is_audited;
    private Boolean is_available;
    private java.util.Date update_time;
    private String publisher_avatar;
    private Integer publisher_id;
    private String publisher_name;
    private Integer publisher_star;
    private String recommend;
    private Integer sold_num;
    private String types;
    private Integer week_activity;

    public Party() {
    }

    public Party(Long id) {
        this.id = id;
    }

    public Party(Long id, String objectId, String title, String only, Integer old_price_man, Integer old_price_woman, Integer price_man, Integer price_woman, java.util.Date end_time, Integer favorite_num, Integer leastnum, Integer sold, String address, String addressurl, String address_thumbnail, String phone, String description, String content, String note, String pic_base_url, java.util.Date created_time, String photoids, String headphoto, String wechatgroup, String customphoto, Integer is_delete, Integer type_ids, Integer limited, Integer maximum_num, java.util.Date start_time, String deadline_time, Integer time_type, String time_text, String user_id, Boolean is_audited, Boolean is_available, java.util.Date update_time, String publisher_avatar, Integer publisher_id, String publisher_name, Integer publisher_star, String recommend, Integer sold_num, String types, Integer week_activity) {
        this.id = id;
        this.objectId = objectId;
        this.title = title;
        this.only = only;
        this.old_price_man = old_price_man;
        this.old_price_woman = old_price_woman;
        this.price_man = price_man;
        this.price_woman = price_woman;
        this.end_time = end_time;
        this.favorite_num = favorite_num;
        this.leastnum = leastnum;
        this.sold = sold;
        this.address = address;
        this.addressurl = addressurl;
        this.address_thumbnail = address_thumbnail;
        this.phone = phone;
        this.description = description;
        this.content = content;
        this.note = note;
        this.pic_base_url = pic_base_url;
        this.created_time = created_time;
        this.photoids = photoids;
        this.headphoto = headphoto;
        this.wechatgroup = wechatgroup;
        this.customphoto = customphoto;
        this.is_delete = is_delete;
        this.type_ids = type_ids;
        this.limited = limited;
        this.maximum_num = maximum_num;
        this.start_time = start_time;
        this.deadline_time = deadline_time;
        this.time_type = time_type;
        this.time_text = time_text;
        this.user_id = user_id;
        this.is_audited = is_audited;
        this.is_available = is_available;
        this.update_time = update_time;
        this.publisher_avatar = publisher_avatar;
        this.publisher_id = publisher_id;
        this.publisher_name = publisher_name;
        this.publisher_star = publisher_star;
        this.recommend = recommend;
        this.sold_num = sold_num;
        this.types = types;
        this.week_activity = week_activity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOnly() {
        return only;
    }

    public void setOnly(String only) {
        this.only = only;
    }

    public Integer getOld_price_man() {
        return old_price_man;
    }

    public void setOld_price_man(Integer old_price_man) {
        this.old_price_man = old_price_man;
    }

    public Integer getOld_price_woman() {
        return old_price_woman;
    }

    public void setOld_price_woman(Integer old_price_woman) {
        this.old_price_woman = old_price_woman;
    }

    public Integer getPrice_man() {
        return price_man;
    }

    public void setPrice_man(Integer price_man) {
        this.price_man = price_man;
    }

    public Integer getPrice_woman() {
        return price_woman;
    }

    public void setPrice_woman(Integer price_woman) {
        this.price_woman = price_woman;
    }

    public java.util.Date getEnd_time() {
        return end_time;
    }

    public void setEnd_time(java.util.Date end_time) {
        this.end_time = end_time;
    }

    public Integer getFavorite_num() {
        return favorite_num;
    }

    public void setFavorite_num(Integer favorite_num) {
        this.favorite_num = favorite_num;
    }

    public Integer getLeastnum() {
        return leastnum;
    }

    public void setLeastnum(Integer leastnum) {
        this.leastnum = leastnum;
    }

    public Integer getSold() {
        return sold;
    }

    public void setSold(Integer sold) {
        this.sold = sold;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddressurl() {
        return addressurl;
    }

    public void setAddressurl(String addressurl) {
        this.addressurl = addressurl;
    }

    public String getAddress_thumbnail() {
        return address_thumbnail;
    }

    public void setAddress_thumbnail(String address_thumbnail) {
        this.address_thumbnail = address_thumbnail;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getPic_base_url() {
        return pic_base_url;
    }

    public void setPic_base_url(String pic_base_url) {
        this.pic_base_url = pic_base_url;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public String getPhotoids() {
        return photoids;
    }

    public void setPhotoids(String photoids) {
        this.photoids = photoids;
    }

    public String getHeadphoto() {
        return headphoto;
    }

    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto;
    }

    public String getWechatgroup() {
        return wechatgroup;
    }

    public void setWechatgroup(String wechatgroup) {
        this.wechatgroup = wechatgroup;
    }

    public String getCustomphoto() {
        return customphoto;
    }

    public void setCustomphoto(String customphoto) {
        this.customphoto = customphoto;
    }

    public Integer getIs_delete() {
        return is_delete;
    }

    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

    public Integer getType_ids() {
        return type_ids;
    }

    public void setType_ids(Integer type_ids) {
        this.type_ids = type_ids;
    }

    public Integer getLimited() {
        return limited;
    }

    public void setLimited(Integer limited) {
        this.limited = limited;
    }

    public Integer getMaximum_num() {
        return maximum_num;
    }

    public void setMaximum_num(Integer maximum_num) {
        this.maximum_num = maximum_num;
    }

    public java.util.Date getStart_time() {
        return start_time;
    }

    public void setStart_time(java.util.Date start_time) {
        this.start_time = start_time;
    }

    public String getDeadline_time() {
        return deadline_time;
    }

    public void setDeadline_time(String deadline_time) {
        this.deadline_time = deadline_time;
    }

    public Integer getTime_type() {
        return time_type;
    }

    public void setTime_type(Integer time_type) {
        this.time_type = time_type;
    }

    public String getTime_text() {
        return time_text;
    }

    public void setTime_text(String time_text) {
        this.time_text = time_text;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Boolean getIs_audited() {
        return is_audited;
    }

    public void setIs_audited(Boolean is_audited) {
        this.is_audited = is_audited;
    }

    public Boolean getIs_available() {
        return is_available;
    }

    public void setIs_available(Boolean is_available) {
        this.is_available = is_available;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

    public String getPublisher_avatar() {
        return publisher_avatar;
    }

    public void setPublisher_avatar(String publisher_avatar) {
        this.publisher_avatar = publisher_avatar;
    }

    public Integer getPublisher_id() {
        return publisher_id;
    }

    public void setPublisher_id(Integer publisher_id) {
        this.publisher_id = publisher_id;
    }

    public String getPublisher_name() {
        return publisher_name;
    }

    public void setPublisher_name(String publisher_name) {
        this.publisher_name = publisher_name;
    }

    public Integer getPublisher_star() {
        return publisher_star;
    }

    public void setPublisher_star(Integer publisher_star) {
        this.publisher_star = publisher_star;
    }

    public String getRecommend() {
        return recommend;
    }

    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    public Integer getSold_num() {
        return sold_num;
    }

    public void setSold_num(Integer sold_num) {
        this.sold_num = sold_num;
    }

    public String getTypes() {
        return types;
    }

    public void setTypes(String types) {
        this.types = types;
    }

    public Integer getWeek_activity() {
        return week_activity;
    }

    public void setWeek_activity(Integer week_activity) {
        this.week_activity = week_activity;
    }

}
