package com.zongbutech.iparty.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String objectId;
    private String openid;
    private String nickname;
    private Integer sex;
    private String province;
    private String city;
    private String country;
    private String headimgurl;
    private String phone;
    private java.util.Date created_time;
    private Integer has_change_sex;
    private String access_token;
    private Integer platform_id;
    private String thirdparty_account;
    private Integer type;
    private java.util.Date update_time;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String objectId, String openid, String nickname, Integer sex, String province, String city, String country, String headimgurl, String phone, java.util.Date created_time, Integer has_change_sex, String access_token, Integer platform_id, String thirdparty_account, Integer type, java.util.Date update_time) {
        this.id = id;
        this.objectId = objectId;
        this.openid = openid;
        this.nickname = nickname;
        this.sex = sex;
        this.province = province;
        this.city = city;
        this.country = country;
        this.headimgurl = headimgurl;
        this.phone = phone;
        this.created_time = created_time;
        this.has_change_sex = has_change_sex;
        this.access_token = access_token;
        this.platform_id = platform_id;
        this.thirdparty_account = thirdparty_account;
        this.type = type;
        this.update_time = update_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getHeadimgurl() {
        return headimgurl;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public java.util.Date getCreated_time() {
        return created_time;
    }

    public void setCreated_time(java.util.Date created_time) {
        this.created_time = created_time;
    }

    public Integer getHas_change_sex() {
        return has_change_sex;
    }

    public void setHas_change_sex(Integer has_change_sex) {
        this.has_change_sex = has_change_sex;
    }

    public String getAccess_token() {
        return access_token;
    }

    public void setAccess_token(String access_token) {
        this.access_token = access_token;
    }

    public Integer getPlatform_id() {
        return platform_id;
    }

    public void setPlatform_id(Integer platform_id) {
        this.platform_id = platform_id;
    }

    public String getThirdparty_account() {
        return thirdparty_account;
    }

    public void setThirdparty_account(String thirdparty_account) {
        this.thirdparty_account = thirdparty_account;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public java.util.Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(java.util.Date update_time) {
        this.update_time = update_time;
    }

}
